application:
  name: the-together-blog-api
  project: the-together-blog-api
  organization: "QoveryCommunity"
  publicly_accessible: true
  cpu: "800m"
  ram: "512mb"
  start_timeout: "480s"
  storage:
  - name: "data"
    size: "10GB"
    type: "ssd"
    mount_point: "/srv/app"
databases:
- type: postgresql
  version: "12.6"
  name: thetogetherblog
routers:
- name: main
  routes:
  - application_name: the-together-blog-api
    paths:
    - "/*"