FROM python:3.9
WORKDIR /app
COPY . .
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1  
ENV DEPLOY 1
ENV DATABASE_CLIENT postgres
ENV DATABASE_HOST ${QOVERY_DATABASE_MY_PSQL_NAME}
ENV DATABASE_PORT ${QOVERY_DATABASE_MY_PSQL_PORT}
ENV DATABASE_NAME ${QOVERY_DATABASE_MY_PSQL_DATABASE}
ENV DATABASE_USERNAME ${QOVERY_DATABASE_MY_PSQL_USERNAME}
ENV DATABASE_PASSWORD ${DATABASE_PASSWORD}
RUN pip install --upgrade pip  
RUN chmod +x start.sh
RUN pip install -r requirements.txt  
RUN rm -rf api/migrations
EXPOSE 1337
CMD ./start.sh